// Module2_FrontEnd/handson_for_angular/student-portal-angular/src/app/course-card/course-card.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-course-card',
    standalone: true,
    imports: [],
    templateUrl: './course-card.html',
    styleUrl: './course-card.css'
})
export class CourseCard {
    @Input() name: string = '';
    @Input() code: string = '';
    @Input() credits: number = 0;
    @Input() grade: string = '';
}

// student-portal-react/src/components/CourseCard.jsx
function CourseCard({ id, name, code, credits, grade, onEnroll }) {
    return (
        <article className="course-card">
            <h3>{name}</h3>
            <p>{code}</p>
            <span>{credits} credits</span>
            <p>Grade: {grade}</p>
            <button onClick={() => onEnroll({ id, name, code, credits, grade })}>
                Enroll
            </button>
        </article>
    )
}

export default CourseCard;
